### ISSUE TITLE
file_exists error

### ISSUE THREAD

**Issue by aswinvk28** [hxtree/LivingMarkup#29]
https://github.com/hxtree/LivingMarkup/blob/master/src/Configuration.php
the above file has got file_exists function which is not a safe call

Please check these links:
https://magento.stackexchange.com/questions/84381/alternative-to-file-exists-function
https://framework.zend.com/manual/2.1/en/modules/zend.validator.file.exists.html

Please also check:
https://www.php.net/manual/en/features.safe-mode.functions.php

file_exists call must be replaced by Zend_Validate_File_Exists

**Comment by hxtree** [comment]
Thanks for bringing this up. I noticed this in the Codacy scan. I would be interested in going the Laminas route (as ZF is no longer supported since it went over to the Linux Foundation).

**Comment by hxtree** [comment]
[https://github.com/laminas/laminas-validator/blob/master/docs/book/validators/file/exists.md](url)

**Comment by hxtree** [comment]
There is Symfony\Component\Filesystem\ exist() is another option that may make more sense than adapting both frameworks (since we are using Symphony for the Yaml checker).
https://symfony.com/doc/current/components/filesystem.html#exists

Interesting, that it's considered not safe as both Zend/Laminas and Symfony call file_exist() in their checks actual checks.

- https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Filesystem/Filesystem.php 
- https://github.com/laminas/laminas-validator/blob/master/src/File/Exists.php

**Comment by hxtree** [comment]
It seems like this is due to max path limitation:
https://stackoverflow.com/questions/11210408/file-exists-incorrectly-returns-false-when-path-is-too-long

**Comment by aswinvk28** [comment]
Thanks for closing the ticket.
